import XCTest

// Shared helpers for the Story Sounds tvOS UI tests.
//
// Everything is driven with the Siri Remote (XCUIRemote). There is no tap on tvOS, so tests move focus with the
// d-pad and press Select. Every loop in this file is bounded; a failure always names what was being looked for.

/// Pure helper that solves the parent-gate adult question from its on-screen text (no app hook needed).
/// Prompts are generated by `AdultChallengeFactory`: "What is 17 × 8 − 23?" or
/// "Add forty-seven and sixty-two, then take away twelve."
enum ParentChallengeSolver {
    private static let ones = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
                               "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen",
                               "eighteen", "nineteen"]
    private static let tens = ["", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"]

    static func wordValue(_ token: String) -> Int? {
        var total = 0
        for part in token.split(separator: "-") {
            let p = String(part)
            if let i = ones.firstIndex(of: p) {
                total += i
            } else if let t = tens.firstIndex(of: p), t >= 2 {
                total += t * 10
            } else {
                return nil
            }
        }
        return token.isEmpty ? nil : total
    }

    static func solve(_ prompt: String) -> Int? {
        let digits = prompt.split(whereSeparator: { !$0.isNumber }).compactMap { Int($0) }
        // Hard variant ("I can't hold the button"): "Multiply 14 by 7, take away 20, then add 9."
        if prompt.hasPrefix("Multiply"), digits.count >= 4 { return digits[0] * digits[1] - digits[2] + digits[3] }
        if digits.count >= 3 { return digits[0] * digits[1] - digits[2] }
        let words = prompt.lowercased().split(whereSeparator: { !($0.isLetter || $0 == "-") })
            .compactMap { wordValue(String($0)) }
        if words.count >= 3 { return words[0] + words[1] - words[2] }
        return nil
    }
}

/// Base class: owns the app, offers focus-driven navigation, flows (onboarding, parent gate) and an activity driver.
class StorySoundsUITestCase: XCTestCase {
    var app: XCUIApplication!

    /// If CI shows container elements reporting focus too, relax this to false (the rest of the suite still checks
    /// that at least one element is focused).
    static let strictSingleFocus = true

    override func setUpWithError() throws {
        try super.setUpWithError()
        continueAfterFailure = false
        app = XCUIApplication()
    }

    override func tearDownWithError() throws {
        app?.terminate()
        try super.tearDownWithError()
    }

    // MARK: Launch

    /// `realHold: true` exercises the real press-and-hold gesture; otherwise the hold step is skipped with
    /// `-uitest-parent-gate-pass` (the adult question is still required).
    func launchApp(reset: Bool = true, inMemory: Bool = true, realHold: Bool = false, extra: [String] = []) {
        var args: [String] = []
        if reset { args.append("-uitest-reset") }
        if inMemory { args.append("-uitest-inmemory") }
        args.append("-uitest-no-audio")
        if !realHold { args.append("-uitest-parent-gate-pass") }
        args.append(contentsOf: extra)
        app.launchArguments = args
        app.launch()
    }

    /// Persistence tests: send the app to the background first (the app flushes saves when the scene leaves the
    /// foreground), wait out the save debounce, terminate, and relaunch WITHOUT -uitest-reset / -uitest-inmemory.
    func relaunchKeepingData(extra: [String] = []) {
        XCUIRemote.shared.press(.home)
        Thread.sleep(forTimeInterval: 2.5)
        app.terminate()
        app.launchArguments = ["-uitest-no-audio", "-uitest-parent-gate-pass"] + extra
        app.launch()
    }

    // MARK: Elements

    /// Any element with this accessibility identifier (button, static text, other).
    func el(_ id: String) -> XCUIElement {
        app.descendants(matching: .any).matching(identifier: id).firstMatch
    }

    func exists(_ id: String) -> Bool { el(id).exists }

    func staticText(beginningWith prefix: String) -> XCUIElement {
        app.descendants(matching: .any).matching(NSPredicate(format: "label BEGINSWITH %@", prefix)).firstMatch
    }

    // MARK: Remote

    func press(_ button: XCUIRemote.Button, settle: TimeInterval = 0.3) {
        XCUIRemote.shared.press(button)
        if settle > 0 { Thread.sleep(forTimeInterval: settle) }
    }

    func directionName(_ b: XCUIRemote.Button) -> String {
        switch b {
        case .up: return "up"
        case .down: return "down"
        case .left: return "left"
        case .right: return "right"
        case .select: return "select"
        case .menu: return "menu"
        case .playPause: return "playPause"
        default: return "button"
        }
    }

    // MARK: Focus

    func focusedElements() -> [XCUIElement] {
        app.descendants(matching: .any).matching(NSPredicate(format: "hasFocus == true")).allElementsBoundByIndex
    }

    /// Identifier of the focused element ("" when none or unlabeled).
    func focusedIdentifier() -> String {
        let all = focusedElements()
        return (all.first(where: { !$0.identifier.isEmpty }) ?? all.first)?.identifier ?? ""
    }

    func focusSignature() -> String {
        let all = focusedElements()
        guard let f = all.first(where: { !$0.identifier.isEmpty }) ?? all.first else { return "none" }
        return "\(f.identifier)|\(f.label)|\(f.frame)"
    }

    @discardableResult
    func waitForFocus(_ e: XCUIElement, timeout: TimeInterval = 5) -> Bool {
        let deadline = Date().addingTimeInterval(timeout)
        while Date() < deadline {
            if e.exists && e.hasFocus { return true }
            Thread.sleep(forTimeInterval: 0.2)
        }
        return e.exists && e.hasFocus
    }

    /// Presses a direction repeatedly until `e.hasFocus`. Bounded: at most 2 rounds x 4 directions x `maxMoves`
    /// presses, and a direction stops early when focus stops changing (an edge). Never loops forever.
    @discardableResult
    func focusElement(_ e: XCUIElement, maxMoves: Int = 8, failOnMiss: Bool = true,
                      file: StaticString = #filePath, line: UInt = #line) -> Bool {
        if !e.exists && !e.waitForExistence(timeout: 10) {
            if failOnMiss { XCTFail("Cannot focus: element '\(e.identifier)' does not exist", file: file, line: line) }
            return false
        }
        if e.hasFocus { return true }
        // Sweep order matters: after moving down into a row of buttons, try left and right BEFORE going back up,
        // otherwise a target in that row (other than the one the focus engine lands on) is never reached.
        let directions: [XCUIRemote.Button] = [.down, .left, .down, .right, .down, .up, .left, .right]
        for _ in 0..<3 {
            for d in directions {
                for _ in 0..<maxMoves {
                    let before = focusSignature()
                    press(d, settle: 0.25)
                    if e.exists && e.hasFocus { return true }
                    if focusSignature() == before { break }   // edge reached in this direction
                }
            }
        }
        if failOnMiss {
            XCTFail("Could not move focus to '\(e.identifier)' within the bounded search. Focused instead: \(focusSignature())",
                    file: file, line: line)
        }
        return false
    }

    /// Focus the element with this identifier and press Select.
    func activate(_ id: String, settle: TimeInterval = 0.6, file: StaticString = #filePath, line: UInt = #line) {
        let e = el(id)
        XCTAssertTrue(e.waitForExistence(timeout: 12), "Expected '\(id)' to exist before activating it", file: file, line: line)
        focusElement(e, file: file, line: line)
        press(.select, settle: settle)
    }

    /// Something must be focused. With `strictSingleFocus`, exactly one element must report focus.
    func assertFocus(_ context: String, file: StaticString = #filePath, line: UInt = #line) {
        var n = focusedElements().count
        let deadline = Date().addingTimeInterval(3)
        while n == 0 && Date() < deadline {
            Thread.sleep(forTimeInterval: 0.25)
            n = focusedElements().count
        }
        XCTAssertGreaterThanOrEqual(n, 1, "\(context): nothing has focus (lost focus)", file: file, line: line)
        if Self.strictSingleFocus {
            XCTAssertLessThanOrEqual(n, 1, "\(context): \(n) elements report focus: \(focusedElements().map { $0.identifier })",
                                     file: file, line: line)
        }
    }

    /// Presses every direction a few times; focus must never disappear.
    func assertDirectionsKeepFocus(_ context: String, file: StaticString = #filePath, line: UInt = #line) {
        let seq: [XCUIRemote.Button] = [.down, .right, .up, .left, .down, .left, .up, .right, .down, .down, .up, .up]
        for d in seq {
            press(d, settle: 0.35)
            assertFocus("\(context) after \(directionName(d))", file: file, line: line)
        }
    }

    // MARK: Child flows

    /// Onboarding -> baseline (skipped or played) -> Home with `home.start` focused.
    func completeOnboarding(nameIndex: Int = 0, playBaseline: Bool = false) {
        XCTAssertTrue(el("onboarding.name.0").waitForExistence(timeout: 20), "Onboarding did not appear")
        focusElement(el("onboarding.name.\(nameIndex)"))
        press(.select, settle: 0.8)
        XCTAssertTrue(el("baseline.start").waitForExistence(timeout: 12), "Baseline intro did not appear")
        if playBaseline {
            activate("baseline.start")
            XCTAssertTrue(el("baseline.prompt").waitForExistence(timeout: 15), "First baseline game did not appear")
            let out = drive(prefix: "baseline", terminals: ["baseline.finish"], maxSteps: 150)
            XCTAssertEqual(out.foundTerminal, "baseline.finish", "Baseline did not reach its end screen (steps: \(out.steps))")
        } else {
            activate("baseline.skip")
        }
        XCTAssertTrue(el("baseline.finish").waitForExistence(timeout: 12), "Baseline outro did not appear")
        activate("baseline.finish", settle: 0.8)
        XCTAssertTrue(el("home.start").waitForExistence(timeout: 12), "Home did not appear after onboarding")
        XCTAssertTrue(waitForFocus(el("home.start")), "home.start should be focused on Home")
    }

    func startSession() {
        activate("home.start", settle: 0.8)
        XCTAssertTrue(el("session.prompt").waitForExistence(timeout: 20), "Session activity did not appear")
    }

    func stickerValue() -> String {
        (el("home.stickers").value as? String) ?? ""
    }

    /// Leaves whatever parent screen is open by pressing Menu (never pressed on Home: that would leave the app).
    func leaveParentToHome() {
        for _ in 0..<4 {
            if exists("home.start") { return }
            press(.menu, settle: 0.8)
        }
        XCTAssertTrue(el("home.start").waitForExistence(timeout: 5), "Could not get back to Home with Menu")
    }

    // MARK: Parent gate

    func openParentGate() {
        activate("home.grownups", settle: 0.8)
        // `parentgate.back` exists at every gate stage (hold, question, locked-out), including when the hold is skipped.
        XCTAssertTrue(el("parentgate.back").waitForExistence(timeout: 10), "Parent gate did not appear")
    }

    func gatePromptElement() -> XCUIElement {
        app.descendants(matching: .any).matching(
            NSPredicate(format: "label BEGINSWITH 'What is ' OR label BEGINSWITH 'Add ' OR label BEGINSWITH 'Multiply '")).firstMatch
    }

    /// Holds Select long enough (the app requires 3 s; 4.5 s adds margin) and waits for the adult question.
    func passHoldStep() {
        // With -uitest-parent-gate-pass the hold step is already skipped and the question is showing.
        if gatePromptElement().waitForExistence(timeout: 2) { return }
        let hold = el("parentgate.hold")
        XCTAssertTrue(hold.waitForExistence(timeout: 10), "Hold control missing")
        waitForFocus(hold)
        XCUIRemote.shared.press(.select, forDuration: 4.5)
        XCTAssertTrue(gatePromptElement().waitForExistence(timeout: 10),
                      "The adult question did not appear after holding Select for 4.5 s. If the long press is not " +
                      "driven by XCUIRemote, the app needs the parent-gate test hook listed under NEEDS.")
    }

    /// Reads the question and returns (correct option index, all option labels).
    func readChallenge() -> (correct: Int, labels: [String]) {
        let prompt = gatePromptElement()
        XCTAssertTrue(prompt.waitForExistence(timeout: 8), "Adult question text not found")
        XCTAssertTrue(el("parentgate.answer.0").waitForExistence(timeout: 8), "Answer buttons not found")
        XCTAssertTrue(el("parentgate.answer.5").waitForExistence(timeout: 4), "Expected six answer options")
        let text = prompt.label
        guard let answer = ParentChallengeSolver.solve(text) else {
            XCTFail("Could not solve the adult question: '\(text)'")
            return (0, [])
        }
        var labels: [String] = []
        // Read every option that exists (six today); bounded so a layout change cannot loop forever.
        var i = 0
        while i < 12 && el("parentgate.answer.\(i)").exists {
            labels.append(el("parentgate.answer.\(i)").label)
            i += 1
        }
        guard let idx = labels.firstIndex(of: "Answer \(answer)") else {
            XCTFail("Computed answer \(answer) from '\(text)' is not among the options \(labels)")
            return (0, labels)
        }
        return (idx, labels)
    }

    func answerChallenge(correct: Bool) {
        let c = readChallenge()
        let index = correct ? c.correct : (c.correct == 0 ? 1 : 0)
        activate("parentgate.answer.\(index)", settle: 0.8)
    }

    /// The gate needs TWO correct answers in a row (each a fresh question). Answers both.
    func answerGateQuestions() {
        answerChallenge(correct: true)
        // The first correct answer shows a new question and the notice "Well done. One more.".
        let step = el("parentgate.step")
        if step.waitForExistence(timeout: 6) {
            let deadline = Date().addingTimeInterval(6)
            while Date() < deadline && !step.label.hasPrefix("Question 2") { Thread.sleep(forTimeInterval: 0.3) }
            XCTAssertTrue(step.label.hasPrefix("Question 2"), "Second question did not appear (step label '\(step.label)')")
        }
        answerChallenge(correct: true)
    }

    /// Home -> hold -> correct answer -> Grown-ups' area menu.
    func unlockParentArea() {
        openParentGate()
        passHoldStep()
        answerGateQuestions()
        XCTAssertTrue(el("parent.menu.progress").waitForExistence(timeout: 12), "Parent menu did not appear after unlocking")
    }

    /// Opens a section card from the parent menu and waits for `readyID`.
    func openParentSection(_ section: String, ready readyID: String) {
        activate("parent.menu.\(section)", settle: 0.8)
        XCTAssertTrue(el(readyID).waitForExistence(timeout: 10), "Section '\(section)' did not show '\(readyID)'")
    }

    /// Settings/Data style pagers: press `<prefix>.next` n times.
    func pageForward(_ prefix: String, times: Int) {
        for _ in 0..<times { activate("\(prefix).next", settle: 0.6) }
    }

    // MARK: Activity driver

    struct DriveOutcome {
        var completions = 0
        var steps = 0
        var foundTerminal: String?
        var stopped = false
    }

    /// Plays activities by pressing Select on whatever the app focuses (the app focuses the sensible control:
    /// first choice, next unused tile, next sound, guided target, Next). Handles choice/tile/slot/sound/page/
    /// fluency/model chrome. Stops when a terminal identifier appears, `stopWhen` is true, `maxCompletions`
    /// activities were finished, or `maxSteps` iterations passed (never loops forever).
    @discardableResult
    func drive(prefix: String, terminals: [String], maxCompletions: Int = Int.max, maxSteps: Int = 400,
               stopWhen: (() -> Bool)? = nil) -> DriveOutcome {
        var out = DriveOutcome()
        var lastSig = ""
        var same = 0
        let nudge: [XCUIRemote.Button] = [.right, .down, .left, .up]
        let nextID = prefix + ".next"
        while out.steps < maxSteps {
            out.steps += 1
            for t in terminals where exists(t) {
                out.foundTerminal = t
                return out
            }
            if let s = stopWhen, s() {
                out.stopped = true
                return out
            }
            if out.completions >= maxCompletions { return out }

            if exists(nextID) {
                selectOn(nextID)
                out.completions += 1
                Thread.sleep(forTimeInterval: 0.6)
                lastSig = ""; same = 0
                continue
            }
            if exists(prefix + ".model.next") {
                selectOn(prefix + ".model.next")
                continue
            }
            if exists(prefix + ".done") {
                selectOn(prefix + ".done")
                continue
            }
            if exists(prefix + ".page.next") {
                selectOn(prefix + ".page.next")
                continue
            }
            // Generic: press Select on the focused answer control.
            let sig = focusSignature()
            let f = focusedIdentifier()
            same = (sig == lastSig) ? same + 1 : 0
            lastSig = sig
            if f.isEmpty || f == prefix + ".hearAgain" || f == prefix + ".hearSlow" {
                press(.down, settle: 0.3)
            } else if same >= 6 {
                press(nudge[same % nudge.count], settle: 0.3)
            } else {
                press(.select, settle: 0.45)
            }
        }
        return out
    }

    /// Select on a specific control without failing the test when focus search misses.
    func selectOn(_ id: String) {
        let e = el(id)
        if e.exists && !e.hasFocus { focusElement(e, maxMoves: 6, failOnMiss: false) }
        press(.select, settle: 0.45)
    }

    // MARK: Text checks

    static let bannedWords = ["wrong", "fail", "incorrect"]

    func allVisibleTexts() -> [String] {
        var out = app.staticTexts.allElementsBoundByIndex.map { $0.label }
        out += app.buttons.allElementsBoundByIndex.map { $0.label }
        return out
    }

    func assertCalmText(_ texts: [String], context: String, file: StaticString = #filePath, line: UInt = #line) {
        for t in texts {
            let lower = t.lowercased()
            for w in Self.bannedWords {
                XCTAssertFalse(lower.contains(w), "\(context): text '\(t)' contains '\(w)'", file: file, line: line)
            }
        }
    }
}
