/**
 * AUTHORING SOURCE: decodable sentences and stories (all original text), plus the names used in them.
 * Every non-tricky token must be either in the word list or in NAMES. The build derives tokens,
 * graphemes and unlockedByOrder; the validator re-checks everything.
 */

/** Names are decodable proper nouns (not in the words list). Segmentation is explicit. */
export const NAMES: Record<string, string> = {
  Pip: 'p-i-p', Sam: 's-a-m', Tim: 't-i-m', Dan: 'd-a-n', Nan: 'n-a-n', Pam: 'p-a-m', Tom: 't-o-m',
  Meg: 'm-e-g', Ben: 'b-e-n', Jen: 'j-e-n', Kit: 'k-i-t', Gus: 'g-u-s', Max: 'm-a-x', Zak: 'z-a-k',
  Viv: 'v-i-v', Jack: 'j-a-ck', Bill: 'b-i-ll', Jim: 'j-i-m', Liz: 'l-i-z', Frog: 'f-r-o-g', Crab: 'c-r-a-b',
  Kate: 'k-a_e-t', Dave: 'd-a_e-v', Paul: 'p-au-l',
};

/** Standalone sentences, roughly in teaching order. */
export const SENTENCES: string[] = [
  // Phase 2
  'Pip sat.', 'Tap it, Pip.', 'Sit, Pip, sit.',
  'Pip sat in a tin.', 'The pin is in the tin.',
  'I am Tim.', 'Pam pats Pip.',
  'Dad sat in a tin.', 'Dad did a nap.',
  'Pip digs a pit.', 'The pig sat in a pit.',
  'The dog sat on a mat.', 'Tom got a mop.', 'A dog is on top.',
  'A cat sat on a cot.', 'Can a cat nap on a mat?',
  'Kit is a kid.', 'Kit is in a cot.',
  'Tom can kick a sock.', 'Pick a sock, Kit.',
  'Meg got a pen.', 'The men set the net.',
  'The pup sat in the sun.', 'Mum got a cup.', 'Dad dug in the mud.',
  'Ben ran on the rug.', 'A red rat ran up.',
  'The hen sat on a hat.', 'Dad can hug Mum.', 'Pam hid in a hut.',
  'The big bug is in the bin.', 'Ben got a bat.',
  'Ben fed the hen.', 'Dad is fit.',
  'The lid is on the log.', 'The dog licks the cup.',
  'Dad can huff and puff.', 'The dog ran off.',
  'The bell is on the hill.', 'Bill fell off the hill.',
  'Mum can kiss the pup.', 'The cat is on the moss.',
  'Jim got a jam bun.', 'Jen and Jack jog.',
  'The van is red.', 'Viv got in the van.', 'The vet pats the pup.',
  'The wet pup can wag.', 'I will win a wig.',
  'Max got a box.', 'The fox is in the box.', 'Dad can fix the van.',
  'Yes, the pup is wet.', 'Yum, a jam bun!',
  'Zak can zip it.', 'Zip the bag, Zak.',
  'The bug can buzz.', 'Buzz, buzz, buzz!',
  'The duck can quack.', 'Quick, Dad, run!',
  'I can chop a log.', 'The chick can peck the chip.',
  'The fish is in the dish.', 'Mum shut the shed.',
  'Dad and I had a bath.', 'The moth sat on the path.', 'This is the thick mud.',
  'The king sang a song.', 'I can sing a long song.',
  'I think the tank is pink.', 'I can wink.',
  // Phase 3
  'The rain fell on the pail.', 'I wait in the rain.',
  'I see a bee.', 'We see the sheep.', 'I keep a seed in a cup.',
  'The light is on at night.', 'I might see a light.',
  'The goat sat in the boat.', 'Tim got a coat.', 'Soap is in the bath.',
  'My cat sat on my coat.', 'They see the boat.', 'Dad is by the boat.',
  'We go to the zoo.', 'The moon is up.', 'It is cool in the pool.', 'All the pups sat in the pool.',
  'Look at the book.', 'Dad can cook good food.', 'The book was good.',
  'The car is in the park.', 'Mum and Dad park the car.', 'I am in the car park.',
  'A fork is for corn.', 'The horn is short.', 'The sheep are on the farm.',
  'The church is on the hill.', 'The cat has fur.', 'I am sure the soap is in the bath.',
  'The cow is in the town.', 'Wow, a big owl!', 'The owl sat down.',
  'The coin is in the soil.', 'Join in, Tim.',
  'I hear a car.', 'I hear the king sing.',
  'Meg sat on the chair.', 'A pair of socks is on the chair.',
  'Dad had a letter.', 'I had dinner with Mum.', 'Sam hit the nail with a hammer.',
  // Phase 4
  'Dad went to get the milk.', 'The tent is on the sand.', 'Help me lift the box.',
  'The ant is on my hand.', 'Jump, Jim, jump!', 'The lamp is on the desk.', 'Pam felt the soft silk.',
  'I said I like milk.', 'I have a pet ant.',
  'The frog can swim in the pond.', 'Stop the van!', 'Clap, clap, clap!', 'A crab is on the step.',
  'The drum is in the box.', 'Some frogs sit on a log.', 'Come and see the crab.', 'I love my pet frog.',
  'Pam and Meg splash in the pond.', 'The brush is by the sink.', 'The street is long.', 'Tim can scrub the pot.',
  'Here is a little crab.', 'Mum says the pup is wet.', 'We were in the bedroom.', 'Dad has a laptop.',
  'Mum put the toothbrush by the sink.',
  'Tom jumped on the sand.', 'Dad picked the best plum.', 'Meg is the fastest.', 'Dad is helping Mum.',
  'The frog is jumping.', 'We went camping today.', 'What is in the box?', 'There is a pink hat in the box.',
  'One little frog sat on a log.', 'When the sun set, we had a rest.',
  // Year 1
  'We play all day.', 'Pip can stay and play.',
  'The cloud is round.', 'The sound is loud.',
  'The boy has a toy.', 'I enjoy the toy.',
  'I eat a peach on the beach.', 'We eat tea on the beach.',
  'The girl has a red skirt.', 'The girl in the shirt can twirl.',
  'I like pie.', 'The pie and the fries are hot.',
  'The glue is blue.', 'Is it true?', 'I have a clue.',
  'I can play music.', 'The unit is super.',
  'Hello, I am Tom.', 'Hold the post.', 'The old gold coin is cold.',
  'The child is kind.', 'I find a kind child.',
  'The baker has a paper label.', 'We see a zebra.',
  'I bake a cake.', 'Kate can make a game.', 'We came to the lake.', 'The cake is on the plate.',
  'I like to ride a bike.', 'I smile at the kite.', 'We slide at nine.',
  'The bone is in the hole.', 'Rose has a note.', 'I hope the rose is home.',
  'The cube is cute.', 'Use the tube.',
  'These are my pets.',
  'A few birds flew.', 'The crew drew a new sun.',
  'The chief is in the field.', 'I believe in you.',
  'The hawk saw the lawn.', 'I draw a paw.',
  'The wheel is white.', 'Which whale is white?',
  'She goes home on tiptoe.',
  'The boulder is on the hill.',
  'I have a photo of a dolphin.', 'The elephant has a phone.',
  'We see the astronaut launch.',
  'The turkey has a key.', 'The key is in the valley.',
  'The snow is on the window.', 'I see a yellow rainbow.',
  'I have bread for breakfast.', 'The feather is on my head.',
  'I try to fly a kite.', 'The sky is dry.',
  'The puppy is happy.', 'The bunny is funny.',
  'The city is nice.', 'Mice like rice.', 'I dance in space.',
  'A magic gem is in the cage.', 'The giraffe is on the page.',
  'A badge is on the bridge.', 'The judge sat on the edge.',
  'I catch the match.', 'Mum can fetch a patch.',
  'I know the knight.', 'I knit a hat.',
  'I write a note.', 'Wrap the gift.',
  'I climb the hill.', 'I comb the lamb.',
  'The gnat is on the sign.',
  'The school has an echo.',
  'I use a parachute.',
  'I wash the wand.', 'The swan is in the swamp.', 'Watch the wasp.',
  'The worm is in the world.',
  'I see a picture of nature.', 'The creature is in the picture.',
  'The train is at the station.', 'I see the television.',
  'Oh, the puppy is muddy.', 'Their house is by the sea.', 'Mrs Jen is kind.', 'You should wash the dish.',
];

export interface PageDef { s: string[]; e?: string; l?: string }
export interface StoryDef { id: string; title: string; pages: PageDef[] }

export const STORIES: StoryDef[] = [
  // ---------- Reception (original) ----------
  { id: 'story-sit-in-the-tin', title: 'Sit in the Tin', pages: [
    { s: ['Pip sat in a tin.'], e: '🥫', l: 'Pip sitting in a tin' },
    { s: ['Tim sat in a tin.'], e: '🥫', l: 'Tim sitting in a tin' },
    { s: ['Nan sat in a tin.'], e: '🥫', l: 'Nan sitting in a tin' },
    { s: ['Dad sat in a tin!'], e: '🥫', l: 'Dad sitting in a tin' },
  ] },
  { id: 'story-dog-on-a-mat', title: 'A Dog on a Mat', pages: [
    { s: ['Dan got a dog.'], e: '🐶', l: 'a boy with a dog' },
    { s: ['The dog sat on a mat.'], e: '🐕', l: 'a dog on a mat' },
    { s: ['The dog did a nap.'], e: '😴', l: 'a dog asleep' },
  ] },
  { id: 'story-the-big-bug', title: 'The Big Bug', pages: [
    { s: ['A big bug sat on a log.'], e: '🐛', l: 'a big bug on a log' },
    { s: ['The bug hid in the mud.'], e: '🌱', l: 'a bug hiding in mud' },
    { s: ['Ben dug in the mud.'], e: '⛏️', l: 'Ben digging' },
    { s: ['Ben let the bug hop on a hat.'], e: '🎩', l: 'a bug on a hat' },
  ] },
  { id: 'story-max-and-the-fox', title: 'Max and the Fox', pages: [
    { s: ['Max got a box.'], e: '📦', l: 'a box' },
    { s: ['A wet fox sat in the box.'], e: '🦊', l: 'a wet fox in a box' },
    { s: ['Max put a rug in the box.'], e: '🧺', l: 'a rug in a box' },
    { s: ['The fox had a nap.', 'Max did a jig.'], e: '😴', l: 'a fox asleep' },
  ] },
  { id: 'story-mud-bath', title: 'Mud Bath', pages: [
    { s: ['The pup ran in the thick mud.'], e: '🐶', l: 'a pup in mud' },
    { s: ['Then the pup sat in a pit.'], e: '🕳️', l: 'a pup in a pit' },
    { s: ['Mum put the pup in a bath.'], e: '🛁', l: 'a pup in a bath' },
    { s: ['Mum did kiss the pup.'], e: '💋', l: 'Mum kissing the pup' },
  ] },
  { id: 'story-the-kings-ring', title: "The King's Ring", pages: [
    { s: ['The king had a pink ring.'], e: '👑', l: 'a king with a pink ring' },
    { s: ['The ring fell in the sink.'], e: '🚰', l: 'a ring in a sink' },
    { s: ['The king did think and think.'], e: '💭', l: 'the king thinking' },
    { s: ['Then he got the ring back.', 'The king sang a song.'], e: '🎵', l: 'the king singing' },
  ] },
  { id: 'story-night-light', title: 'Night Light', pages: [
    { s: ['It is night.'], e: '🌙', l: 'night time' },
    { s: ['The light is on.'], e: '💡', l: 'a light' },
    { s: ['I see the moon.'], e: '🌙', l: 'the moon' },
    { s: ['I keep the light on all night.'], e: '💡', l: 'a light on at night' },
  ] },
  { id: 'story-goat-in-the-boat', title: 'The Goat in the Boat', pages: [
    { s: ['A goat sat in a boat.'], e: '🐐', l: 'a goat in a boat' },
    { s: ['The rain fell on the goat.'], e: '🌧️', l: 'rain falling' },
    { s: ['The goat got a coat.'], e: '🧥', l: 'a goat in a coat' },
    { s: ['The goat sat in the boat in the rain.'], e: '⛵', l: 'a goat in a boat in the rain' },
  ] },
  { id: 'story-at-the-zoo', title: 'At the Zoo', pages: [
    { s: ['We go to the zoo.'], e: '🦓', l: 'a zoo' },
    { s: ['I see a big cat on a rock.'], e: '🐈', l: 'a big cat on a rock' },
    { s: ['I look at the pool.', 'It is cool.'], e: '🏊', l: 'a cool pool' },
    { s: ['The zoo is good.'], e: '😊', l: 'a happy child' },
  ] },
  { id: 'story-the-farm', title: 'The Farm', pages: [
    { s: ['Mum and Dad park the car at the farm.'], e: '🚜', l: 'a farm' },
    { s: ['The cow is in the barn.'], e: '🐄', l: 'a cow in a barn' },
    { s: ['I hear the horn.'], e: '📯', l: 'a horn' },
    { s: ['A hen sat on a chair in the barn.'], e: '🐔', l: 'a hen on a chair' },
  ] },
  { id: 'story-frog-and-crab', title: 'Frog and Crab', pages: [
    { s: ['Frog sat on a log by the pond.'], e: '🐸', l: 'a frog on a log' },
    { s: ['Crab ran up the bank.'], e: '🦀', l: 'a crab on the bank' },
    { s: ['Crab said, "Can I swim in the pond?"'], e: '🦀', l: 'a crab asking a question' },
    { s: ['Frog said, "Yes! Jump in."'], e: '🐸', l: 'a frog inviting' },
  ] },
  { id: 'story-camping', title: 'Camping', pages: [
    { s: ['Tom and Meg went camping today.'], e: '⛺', l: 'two children camping' },
    { s: ['They set up a tent.'], e: '⛺', l: 'a tent' },
    { s: ['Tom had a snack in the tent.'], e: '🍪', l: 'a snack' },
    { s: ['Then the sun went down.', 'They had a rest.'], e: '🌅', l: 'a sunset' },
  ] },
  { id: 'story-the-red-bus', title: 'The Red Bus', pages: [
    { s: ['Today I am on a bus.'], e: '🚌', l: 'a bus' },
    { s: ['The bus is red.'], e: '🔴', l: 'a red bus' },
    { s: ['We stop at a big shop.'], e: '🛍️', l: 'a shop' },
    { s: ['I like the bus.'], e: '😊', l: 'a happy child' },
  ] },
  { id: 'story-whats-in-the-box', title: 'What Is in the Box?', pages: [
    { s: ['What is in the box?'], e: '📦', l: 'a box' },
    { s: ['There is a pink hat in the box.'], e: '🎩', l: 'a pink hat' },
    { s: ['There is a drum in the box.'], e: '🥁', l: 'a drum' },
    { s: ['There is one little frog in the box!'], e: '🐸', l: 'a little frog' },
  ] },
  // ---------- Year 1 (lighter) ----------
  { id: 'story-a-day-at-the-beach', title: 'A Day at the Beach', pages: [
    { s: ['We play on the beach today.'], e: '🏖️', l: 'a beach' },
    { s: ['I eat a peach.'], e: '🍑', l: 'a peach' },
    { s: ['The sea is deep and blue.'], e: '🌊', l: 'the sea' },
    { s: ['We stay all day.'], e: '🌞', l: 'a sunny day' },
  ] },
  { id: 'story-the-kind-baker', title: 'The Kind Baker', pages: [
    { s: ['The baker can bake a cake.'], e: '🎂', l: 'a cake' },
    { s: ['The cake is on a plate.'], e: '🍽️', l: 'a cake on a plate' },
    { s: ['Kate can take the cake home.'], e: '🏠', l: 'a girl carrying a cake home' },
    { s: ['Kate and Dad like the cake.'], e: '😋', l: 'happy eaters' },
  ] },
  { id: 'story-the-happy-puppy', title: 'The Happy Puppy', pages: [
    { s: ['The puppy is happy.'], e: '🐶', l: 'a happy puppy' },
    { s: ['The puppy can run in the mud.'], e: '🏃', l: 'a puppy running' },
    { s: ['The puppy is muddy.'], e: '🟤', l: 'a muddy puppy' },
    { s: ['The puppy sat in a bath.'], e: '🛁', l: 'a puppy in a bath' },
    { s: ['The puppy is clean and happy.'], e: '✨', l: 'a clean puppy' },
  ] },
  { id: 'story-the-knight-and-the-wren', title: 'The Knight and the Wren', pages: [
    { s: ['The knight is on a hill.'], e: '🛡️', l: 'a knight on a hill' },
    { s: ['He can see a wren.'], e: '🐦', l: 'a small bird' },
    { s: ['The wren sat on his wrist.'], e: '🐦', l: 'a bird on a wrist' },
    { s: ['The knight wrote a note.'], e: '📝', l: 'a note' },
  ] },
];
