/**
 * AUTHORING SOURCE: decodable words grouped by the unit at which they unlock.
 * Entry syntax:  "seg-ment-ation[@req1+req2][|emoji[|picture label]]"
 *  - segmentation is dash separated graphemes; split digraphs written like "a_e" (cake = c-a_e-k).
 *  - @reqN are extra unit keys that must be taught first (pronunciation-aware gating, e.g. long 'o' in "old").
 * Group key = unit key (no "g-" prefix) or a Phase 4 consolidation key ("p4-cvcc" ...). A group's words must
 * unlock exactly at that unit (Phase 4 groups: at or before it; the Phase 4 unit is then added as a requirement
 * so pedagogically-later patterns like CVCC are not offered early).
 * No tricky words (is, the, was, ...) appear here; they live in the tricky list.
 */
export const WORDS: Record<string, string[]> = {
  s: [],
  a: ['a'],
  t: ['a-t', 's-a-t'],
  p: ['t-a-p|🚰|tap', 'p-a-t', 's-a-p', 't-a-p-s', 'p-a-t-s'],
  i: ['i-t', 's-i-t', 's-i-p', 't-i-p', 'p-i-t', 'p-i-p', 's-i-t-s', 't-i-p-s', 'p-i-t-s', 's-i-p-s', 'p-i-p-s'],
  n: ['a-n', 'i-n', 'n-a-p|😴|nap', 'p-i-n|📌|pin', 't-i-n|🥫|tin', 'p-a-n|🍳|pan', 't-a-n', 'n-i-p', 'p-i-n-s|📌|pins', 't-i-n-s|🥫|tins', 'p-a-n-s|🍳|pans', 'n-a-p-s'],
  m: ['a-m', 'm-a-t', 'm-a-p|🗺️|map', 'm-a-n|👨|man', 'm-a-t-s', 'm-a-p-s|🗺️|maps'],
  d: ['d-a-d', 'd-i-d', 'd-i-p', 'd-i-m', 'm-a-d', 's-a-d|😢|sad', 'p-a-d', 'd-a-d-s', 'p-a-d-s', 'd-i-p-s'],
  g: ['p-i-g|🐷|pig', 'd-i-g', 'g-a-p', 't-a-g|🏷️|tag', 'n-a-g', 's-a-g', 'g-i-g', 'g-a-s', 'p-i-g-s|🐷|pigs', 'd-i-g-s', 't-a-g-s|🏷️|tags'],
  o: ['o-n', 'd-o-g|🐶|dog', 'p-o-t|🍲|pot', 't-o-p', 'm-o-p|🧹|mop', 'n-o-d', 'p-o-p', 'd-o-t|⚫|dot', 'g-o-t', 'n-o-t', 'p-o-d', 'd-o-g-s|🐶|dogs', 'p-o-t-s|🍲|pots', 't-o-p-s', 'm-o-p-s|🧹|mops'],
  c: ['c-a-t|🐱|cat', 'c-a-p|🧢|cap', 'c-o-t', 'c-a-n|🥫|can', 'c-o-g|⚙️|cog', 'c-o-d', 'c-a-t-s|🐱|cats', 'c-a-p-s|🧢|caps', 'c-a-n-s|🥫|cans', 'c-o-t-s'],
  k: ['k-i-t|🧰|kit', 'k-i-d|🧒|kid', 'k-i-t-s|🧰|kits', 'k-i-d-s|🧒|kids'],
  ck: ['p-a-ck', 'p-i-ck', 's-i-ck|🤒|sick', 't-i-ck', 'k-i-ck', 's-o-ck|🧦|sock', 'd-o-ck', 't-a-ck', 'p-i-ck-s', 's-o-ck-s|🧦|socks', 'k-i-ck-s', 'p-a-ck-s'],
  e: ['p-e-n|🖊️|pen', 'p-e-g', 'n-e-t|🥅|net', 'm-e-n|👥|men', 't-e-n|🔟|ten', 'g-e-t', 's-e-t', 'm-e-t', 'p-e-t', 'd-e-n', 'p-e-ck', 'n-e-ck', 'e-g-g|🥚|egg', 'p-e-n-s|🖊️|pens', 'n-e-t-s|🥅|nets', 'p-e-t-s', 'e-g-g-s|🥚|eggs'],
  u: ['u-s', 'u-p', 'm-u-m|👩|mum', 's-u-n|☀️|sun', 'm-u-d', 'c-u-p|☕|cup', 'p-u-p|🐶|pup', 'n-u-t|🥜|nut', 'g-u-m', 'c-u-t|✂️|cut', 'm-u-g|☕|mug', 'd-u-g', 't-u-g', 'd-u-ck|🦆|duck', 't-u-ck', 'c-u-p-s|☕|cups', 'p-u-p-s|🐶|pups', 'n-u-t-s|🥜|nuts', 'm-u-g-s|☕|mugs', 'd-u-ck-s|🦆|ducks'],
  r: ['r-a-t|🐀|rat', 'r-a-n', 'r-i-p', 'r-i-m', 'r-i-d', 'r-u-n|🏃|run', 'r-u-g', 'r-e-d|🔴|red', 'r-o-d', 'r-a-m', 'r-o-ck|🪨|rock', 'r-a-ck', 'r-u-n-s', 'r-a-t-s|🐀|rats', 'r-u-g-s', 'r-o-ck-s|🪨|rocks'],
  h: ['h-a-t', 'h-e-n|🐔|hen', 'h-i-p', 'h-o-t|🔥|hot', 'h-u-g|🤗|hug', 'h-u-m', 'h-u-t|🛖|hut', 'h-o-p', 'h-i-d', 'h-i-m', 'h-a-m', 'h-i-t', 'h-a-d', 'h-a-t-s', 'h-e-n-s|🐔|hens', 'h-u-t-s|🛖|huts', 'h-u-g-s|🤗|hugs'],
  b: ['b-a-t|🦇|bat', 'b-a-g|👜|bag', 'b-e-d|🛏️|bed', 'b-i-g', 'b-i-n|🗑️|bin', 'b-u-s|🚌|bus', 'b-u-g|🐛|bug', 'b-u-n', 'b-i-b', 'b-i-t', 'b-a-d', 't-u-b|🛁|tub', 'c-a-b', 'r-u-b', 'b-a-ck', 'b-u-d', 'b-a-t-s|🦇|bats', 'b-a-g-s|👜|bags', 'b-e-d-s|🛏️|beds', 'b-u-g-s|🐛|bugs', 'b-i-n-s|🗑️|bins', 'b-u-n-s'],
  f: ['f-a-n', 'f-i-n', 'f-i-g', 'f-i-t', 'f-a-t', 'f-u-n', 'f-o-g|🌫️|fog', 'f-e-d', 'f-i-b', 'i-f', 'f-i-n-s', 'f-a-n-s', 'f-i-g-s'],
  l: ['l-e-g|🦵|leg', 'l-i-p|👄|lip', 'l-a-p', 'l-o-g|🪵|log', 'l-i-d', 'l-e-t', 'l-o-t', 'l-i-t', 'l-u-g', 'l-e-d', 'l-i-ck|👅|lick', 'l-i-ck-s|👅|licks', 'l-o-ck|🔒|lock', 'l-a-ck', 'l-u-ck', 'p-a-l', 'l-a-d', 'l-e-g-s|🦵|legs', 'l-i-p-s|👄|lips', 'l-i-d-s', 'l-o-g-s|🪵|logs'],
  ff: ['o-ff', 'p-u-ff|💨|puff', 'h-u-ff', 'c-u-ff', 'm-u-ff', 'b-u-ff'],
  ll: ['b-e-ll|🔔|bell', 'd-o-ll|🪆|doll', 'h-i-ll|⛰️|hill', 'p-i-ll', 't-e-ll', 'f-i-ll', 'b-i-ll', 'm-i-ll', 'd-u-ll', 'g-u-ll', 's-e-ll', 'f-e-ll', 'h-u-ll', 'b-e-ll-s|🔔|bells', 'h-i-ll-s|⛰️|hills'],
  ss: ['m-e-ss', 'm-i-ss', 'k-i-ss', 'm-o-ss', 'b-o-ss', 'h-i-ss', 't-o-ss', 'f-u-ss', 'p-a-ss', 'l-e-ss', 'l-o-ss', 'm-a-ss'],
  j: ['j-a-m', 'j-e-t|✈️|jet', 'j-u-g', 'j-o-g|🏃|jog', 'j-o-b', 'j-i-g', 'j-o-t', 'j-a-m-s', 'j-e-t-s|✈️|jets', 'j-u-g-s', 'j-o-b-s'],
  v: ['v-a-n|🚐|van', 'v-e-t|🩺|vet', 'v-a-t', 'v-i-m', 'v-a-n-s|🚐|vans', 'v-e-t-s|🩺|vets'],
  w: ['w-e-b|🕸️|web', 'w-e-t', 'w-i-n', 'w-i-g', 'w-a-g', 'w-e-d', 'w-o-k|🍳|wok', 'w-e-ll', 'w-i-ll', 'w-i-ck', 'w-e-b-s|🕸️|webs', 'w-i-g-s'],
  x: ['o-x|🐂|ox', 'b-o-x|📦|box', 'f-o-x|🦊|fox', 's-i-x|6️⃣|six', 'm-i-x', 'f-i-x|🔧|fix', 'w-a-x', 't-a-x'],
  y: ['y-e-s', 'y-a-p', 'y-a-m|🍠|yam', 'y-a-k', 'y-e-t', 'y-u-m|😋|yum', 'y-e-ll|📣|yell', 'y-u-ck|🤢|yuck'],
  z: ['z-i-p|🤐|zip', 'z-a-p|⚡|zap', 'z-e-d', 'z-i-p-s|🤐|zips', 'z-a-p-s|⚡|zaps'],
  zz: ['b-u-zz', 'f-i-zz|🫧|fizz', 'j-a-zz|🎷|jazz', 'f-u-zz'],
  qu: ['qu-i-t', 'qu-i-z|❓|quiz', 'qu-i-ck', 'qu-a-ck', 'qu-i-ll|🪶|quill', 'qu-i-p'],
  ch: ['ch-i-p|🍟|chip', 'ch-o-p', 'ch-i-n', 'ch-a-t|💬|chat', 'ch-e-ck|✅|check', 'ch-i-ck|🐥|chick', 'ch-a-p', 'm-u-ch', 's-u-ch', 'r-i-ch', 'ch-u-g', 'ch-u-m', 'ch-i-ll', 'ch-e-ss|♟️|chess', 'ch-i-p-s|🍟|chips', 'ch-o-p-s'],
  sh: ['sh-i-p', 'sh-o-p|🛍️|shop', 'sh-e-d', 'sh-e-ll|🐚|shell', 'f-i-sh|🐟|fish', 'd-i-sh|🍽️|dish', 'w-i-sh|🌠|wish', 'r-u-sh|🏃|rush', 'm-a-sh', 'c-a-sh|💵|cash', 'sh-u-t', 'sh-i-n', 'sh-o-ck', 'sh-a-ck', 'h-u-sh', 'sh-i-p-s', 'sh-o-p-s|🛍️|shops'],
  // Unvoiced /th/ (thin): tongue between the teeth, air only.
  th: ['th-i-n', 'th-i-ck', 'm-o-th', 'b-a-th|🛁|bath', 'p-a-th|🛤️|path', 'th-u-d'],
  // Voiced /dh/ (this): same tongue position with the voice on. Every voiced-th word is gated here (even later ones, via @th-voiced).
  'th-voiced': ['th-i-s@th-voiced', 'th-a-t@th-voiced', 'th-e-n@th-voiced', 'th-e-m@th-voiced', 'w-i-th@th-voiced', 'th-a-n@th-voiced'],
  ng: ['r-i-ng|💍|ring', 'k-i-ng|🤴|king', 's-o-ng|🎵|song', 's-i-ng|🎤|sing', 'w-i-ng', 'l-o-ng', 'h-a-ng', 'b-a-ng', 'r-a-ng', 's-a-ng', 'g-o-ng', 'f-a-ng', 'h-u-ng', 'l-u-ng|🫁|lung', 'th-i-ng', 'p-i-ng', 's-u-ng', 'r-u-ng', 'r-i-ng-s|💍|rings', 'k-i-ng-s|🤴|kings'],
  nk: ['b-a-nk|🏦|bank', 'p-i-nk', 's-i-nk', 'j-u-nk', 'h-o-nk', 't-a-nk', 'th-i-nk|🤔|think', 'th-a-nk', 's-u-nk', 'w-i-nk|😉|wink', 'l-i-nk', 'i-nk|🖋️|ink', 'b-u-nk', 'd-u-nk', 'r-a-nk', 'y-a-nk'],

  // ---- Phase 3 ----
  ai: ['r-ai-n|🌧️|rain', 't-ai-l', 'm-ai-l|✉️|mail', 'p-ai-d', 'n-ai-l', 'p-ai-l|🪣|pail', 'w-ai-t', 's-ai-l', 'r-ai-l', 'm-ai-n', 'p-ai-n', 'ch-ai-n|⛓️|chain', 'g-ai-n', 'f-ai-l', 'b-ai-t', 'l-ai-d', 'm-ai-d', 'r-ai-n-s|🌧️|rains', 't-ai-l-s'],
  ee: ['s-ee|👀|see', 'b-ee|🐝|bee', 'f-ee-t|🦶|feet', 's-ee-d|🌱|seed', 'n-ee-d', 'w-ee-k|📅|week', 'k-ee-p', 'd-ee-p', 'f-ee-l', 'p-ee-l|🍌|peel', 's-ee-m', 't-ee-th|🦷|teeth', 'ch-ee-k', 'sh-ee-p|🐑|sheep', 'sh-ee-t', 'j-ee-p', 'w-ee-d', 'b-ee-p', 'p-ee-p', 'f-ee-d', 'b-ee-s|🐝|bees', 's-ee-d-s|🌱|seeds'],
  igh: ['h-igh', 's-igh', 'th-igh', 'n-igh-t|🌃|night', 'l-igh-t|💡|light', 'r-igh-t', 's-igh-t', 'f-igh-t', 'm-igh-t', 't-igh-t', 'n-igh', 'l-igh-t-s|💡|lights', 'n-igh-t-s|🌃|nights'],
  oa: ['b-oa-t|⛵|boat', 'c-oa-t|🧥|coat', 'g-oa-t|🐐|goat', 's-oa-p|🧼|soap', 'r-oa-d|🛣️|road', 't-oa-d', 'm-oa-n', 'l-oa-d', 'f-oa-m', 'l-oa-f|🍞|loaf', 'c-oa-ch|🚌|coach', 's-oa-k', 'r-oa-m', 'g-oa-l', 'oa-k', 'b-oa-t-s|⛵|boats', 'c-oa-t-s|🧥|coats', 'g-oa-t-s|🐐|goats'],
  'oo-long': ['z-oo', 't-oo', 'm-oo-n|🌙|moon', 'f-oo-d', 'b-oo-t|🥾|boot', 'h-oo-p', 'r-oo-f', 'p-oo-l', 'c-oo-l', 'r-oo-m', 's-oo-n', 'n-oo-n', 'b-oo-m', 'z-oo-m', 'h-oo-t', 't-oo-th|🦷|tooth', 'b-oo-t-s|🥾|boots', 'z-oo-s'],
  'oo-short': ['b-oo-k@oo-short|📖|book', 'l-oo-k@oo-short|👀|look', 'f-oo-t@oo-short|🦶|foot', 'g-oo-d@oo-short', 'w-oo-d@oo-short|🪵|wood', 'c-oo-k@oo-short|🧑‍🍳|cook', 'h-oo-k@oo-short|🪝|hook', 't-oo-k@oo-short', 'w-oo-l@oo-short|🧶|wool', 'h-oo-d@oo-short', 'n-oo-k@oo-short', 'w-oo-f@oo-short', 'b-oo-k-s@oo-short|📖|books', 'l-oo-k-s@oo-short'],
  ar: ['c-ar|🚗|car', 'f-ar-m|🚜|farm', 'p-ar-k', 'c-ar-t|🛒|cart', 'd-ar-k', 'c-ar-d|🃏|card', 'j-ar', 'b-ar', 'f-ar', 'ar-m|💪|arm', 'ar-t|🎨|art', 'h-ar-d', 'y-ar-d', 'm-ar-k', 'sh-ar-k|🦈|shark', 'b-ar-n', 'h-ar-m', 'p-ar-t', 'ch-ar-m', 'c-ar-s|🚗|cars', 'f-ar-m-s|🚜|farms', 'ar-m-s|💪|arms'],
  or: ['or', 'f-or', 'f-or-k|🍴|fork', 'c-or-n|🌽|corn', 'h-or-n|📯|horn', 'b-or-n', 'c-or-d', 'f-or-t|🏰|fort', 's-or-t', 't-or-n', 'p-or-k', 'c-or-k', 'sh-or-t', 'n-or-th', 'f-or-m', 'm-or-n-i-ng|🌅|morning', 'f-or-k-s|🍴|forks', 'h-or-n-s|📯|horns'],
  ur: ['f-ur', 'ur-n', 'b-ur-n', 't-ur-n', 'h-ur-t', 'c-ur-l', 'ch-ur-ch|⛪|church', 's-ur-f|🏄|surf', 'p-ur-r', 'b-ur-p', 'c-ur-b', 'h-ur-l', 't-ur-f', 'f-ur-s'],
  ow: ['c-ow|🐄|cow', 'n-ow', 'h-ow', 'w-ow', 'd-ow-n|⬇️|down', 't-ow-n|🏘️|town', 'ow-l|🦉|owl', 'g-ow-n|👗|gown', 'h-ow-l', 'v-ow', 'f-ow-l|🐔|fowl', 'c-ow-s|🐄|cows', 'ow-l-s|🦉|owls', 't-ow-n-s|🏘️|towns'],
  oi: ['oi-l|🛢️|oil', 'c-oi-n|🪙|coin', 'b-oi-l', 's-oi-l', 'j-oi-n', 'f-oi-l', 't-oi-l', 'c-oi-l', 'c-oi-n-s|🪙|coins', 'oi-l-s'],
  ear: ['ear|👂|ear', 'h-ear', 'n-ear', 'd-ear', 'f-ear', 'y-ear', 'g-ear|⚙️|gear', 'r-ear', 'ear-s|👂|ears', 'y-ear-s'],
  air: ['air', 'f-air|🎡|fair', 'h-air|💇|hair', 'p-air', 'ch-air|🪑|chair', 'l-air', 'ch-air-s|🪑|chairs', 'h-air-s'],
  er: ['l-e-t-t-er|✉️|letter', 'h-a-m-m-er|🔨|hammer', 'l-a-d-d-er|🪜|ladder', 'd-i-n-n-er|🍝|dinner', 's-u-p-p-er|🍝|supper', 's-u-m-m-er', 'b-u-t-t-er|🧈|butter', 'b-e-t-t-er', 'b-i-g-g-er', 'r-u-b-b-er', 'n-e-v-er', 'r-i-v-er|🏞️|river', 'e-v-er', 'l-e-t-t-er-s|✉️|letters', 'l-a-d-d-er-s|🪜|ladders'],

  // ---- Phase 4 (consolidation; gated at the Phase 4 unit) ----
  'p4-cvcc': ['a-n-t|🐜|ant', 'r-e-s-t|🛋️|rest', 't-e-n-t|⛺|tent', 'n-e-s-t', 'h-a-n-d|✋|hand', 'm-i-l-k|🥛|milk', 'l-a-m-p', 'b-e-l-t', 'd-e-s-k', 'h-e-l-p', 'j-u-m-p', 'g-i-f-t|🎁|gift', 's-a-n-d', 'p-o-n-d', 'b-e-s-t', 'w-e-s-t', 'f-a-s-t', 'l-o-s-t', 'm-i-s-t', 'n-e-x-t', 'p-u-m-p', 'c-a-m-p', 's-o-f-t', 'l-e-f-t', 'h-u-n-t', 'b-u-m-p', 's-i-l-k', 'h-e-l-d', 'm-e-l-t', 'f-e-l-t', 'k-e-p-t', 'l-i-f-t', 'l-i-s-t|📝|list', 'd-u-s-t', 'r-u-s-t', 'p-a-s-t', 't-e-s-t', 'w-e-n-t', 's-e-n-t', 'sh-e-l-f', 't-e-n-t-s|⛺|tents', 'a-n-t-s|🐜|ants', 'h-a-n-d-s|✋|hands', 'p-a-n-t-s'],
  'p4-ccvc': ['f-r-o-g|🐸|frog', 'd-r-u-m|🥁|drum', 'c-r-a-b|🦀|crab', 's-t-e-p|👣|step', 'f-l-a-g|🚩|flag', 's-t-o-p|🛑|stop', 's-w-i-m|🏊|swim', 't-r-i-p|🧳|trip', 'p-l-a-n', 'c-l-a-p|👏|clap', 's-n-a-p', 's-k-i-p', 's-p-i-n|🌀|spin', 'g-r-i-n', 'g-r-a-b', 'p-l-u-m', 's-l-i-p', 's-n-u-g', 't-r-a-p', 't-w-i-n', 'd-r-i-p|💧|drip', 'f-l-i-p', 'g-l-a-d', 'c-l-u-b', 's-p-o-t', 'b-l-o-b', 'c-r-i-b', 'c-l-i-p|📎|clip', 'p-l-u-g|🔌|plug', 's-l-u-g', 's-l-e-d|🛷|sled', 'f-l-a-t', 'd-r-e-ss|👗|dress', 's-n-a-ck|🍪|snack', 'c-r-ow-n|👑|crown', 'b-r-ow-n|🟤|brown', 'c-l-ow-n|🤡|clown', 'g-r-ee-n|🟢|green', 't-r-ee|🌳|tree', 's-l-ee-p|😴|sleep', 's-t-ar|⭐|star', 's-n-ai-l|🐌|snail', 't-r-ai-n|🚂|train', 's-p-oo-n|🥄|spoon', 's-t-oo-l', 'f-l-oa-t', 'f-r-o-g-s|🐸|frogs', 'c-r-a-b-s|🦀|crabs', 'd-r-u-m-s|🥁|drums'],
  'p4-long': ['s-t-a-m-p', 'c-r-i-s-p', 'b-r-u-sh|🪥|brush', 's-p-l-a-sh|💦|splash', 's-p-r-i-ng|🌸|spring', 's-t-r-i-ng|🧵|string', 's-t-r-o-ng', 's-c-r-u-b|🧽|scrub', 's-t-r-ee-t|🛣️|street', 's-p-r-i-n-t|🏃|sprint', 't-r-u-nk', 'b-l-i-nk|👁️|blink', 'p-l-a-nk', 'd-r-i-nk|🧃|drink', 's-t-u-m-p', 'g-r-a-n-d', 'f-r-o-s-t', 'c-r-u-s-t', 'c-l-a-m-p', 's-p-l-i-t',
    's-u-n-s-e-t|🌇|sunset', 'l-a-p-t-o-p|💻|laptop', 'h-o-t-d-o-g|🌭|hot dog', 'c-a-t-n-a-p|😴|catnap', 'b-a-ck-p-a-ck|🎒|backpack', 's-u-n-h-a-t', 'b-a-th-t-u-b|🛁|bathtub', 'h-a-n-d-b-a-g|👜|handbag', 'd-u-s-t-b-i-n|🗑️|dustbin', 'p-o-p-c-or-n|🍿|popcorn', 'b-e-d-r-oo-m', 't-oo-th-b-r-u-sh|🪥|toothbrush', 's-u-n-l-igh-t', 'm-oo-n-l-igh-t', 'r-ai-n-c-oa-t|🧥|raincoat', 'air-p-or-t', 'f-ar-m-y-ar-d|🚜|farmyard', 's-t-ar-f-i-sh', 'z-i-g-z-a-g|〰️|zigzag', 'c-o-b-w-e-b|🕸️|cobweb', 'p-i-g-p-e-n'],
  'p4-suffix': ['j-u-m-p-ed', 'h-e-l-p-ed', 'c-a-m-p-ed', 'l-i-f-t-ed', 'p-i-ck-ed', 'k-i-ck-ed', 'p-a-ck-ed', 'p-a-ss-ed', 'r-u-sh-ed', 'f-i-sh-ed|🎣|fished', 'w-i-sh-ed', 'm-i-x-ed', 'f-i-x-ed', 'h-o-p-p-ed',
    'j-u-m-p-i-ng', 's-i-ng-i-ng|🎤|singing', 'h-e-l-p-i-ng', 'c-a-m-p-i-ng', 'r-u-n-n-i-ng|🏃|running', 'd-i-g-g-i-ng|⛏️|digging', 'h-u-g-g-i-ng|🤗|hugging', 's-i-t-t-i-ng', 'c-l-a-p-p-i-ng|👏|clapping', 's-w-i-m-m-i-ng|🏊|swimming', 'd-r-i-p-p-i-ng|💧|dripping', 's-k-i-p-p-i-ng', 's-t-o-p-p-i-ng', 'p-a-ck-i-ng', 'k-i-ck-i-ng', 'l-i-f-t-i-ng',
    'f-a-s-t-e-s-t', 'l-o-ng-e-s-t', 's-t-r-o-ng-e-s-t', 'b-i-g-g-e-s-t', 'th-i-ck-e-s-t', 'qu-i-ck-e-s-t', 'd-ar-k-e-s-t', 's-o-f-t-e-s-t'],

  // ---- Phase 5 (Year 1) ----
  ay: ['d-ay', 'p-l-ay', 's-ay', 's-t-ay', 'w-ay', 'm-ay', 'p-ay', 't-r-ay', 'a-w-ay', 'c-l-ay', 's-p-r-ay', 'h-ay', 'r-ay', 'b-ay', 'l-ay'],
  ou: ['l-ou-d|🔊|loud', 'c-l-ou-d|☁️|cloud', 'm-ou-th', 'sh-ou-t|📢|shout', 'f-ou-n-d', 'r-ou-n-d|⚪|round', 's-ou-n-d|🔉|sound', 'c-ou-n-t', 'g-r-ou-n-d', 's-ou-th', 'p-r-ou-d', 's-c-ou-t', 'a-r-ou-n-d'],
  oy: ['b-oy|👦|boy', 't-oy|🧸|toy', 'j-oy', 'e-n-j-oy', 'a-n-n-oy', 'r-oy-a-l', 'c-ow-b-oy|🤠|cowboy', 'p-l-oy'],
  ea: ['s-ea|🌊|sea', 't-ea|🍵|tea', 'ea-t', 'l-ea-f|🍃|leaf', 'b-ea-ch|🏖️|beach', 't-ea-m', 'p-ea-ch|🍑|peach', 'm-ea-t|🥩|meat', 'm-ea-n', 'c-l-ea-n', 'd-r-ea-m|💭|dream', 'c-r-ea-m', 's-ea-l|🦭|seal', 't-r-ea-t', 'j-ea-n-s|👖|jeans'],
  ir: ['g-ir-l|👧|girl', 'b-ir-d|🐦|bird', 'b-ir-d-s|🐦|birds', 'sh-ir-t|👕|shirt', 'f-ir-s-t', 'th-ir-d', 's-t-ir', 'd-ir-t', 's-k-ir-t', 'b-ir-th', 't-w-ir-l', 's-w-ir-l', 's-ir', 'f-ir'],
  ie: ['p-ie|🥧|pie', 't-ie|👔|tie', 'l-ie', 'f-r-ie-s|🍟|fries', 'c-r-ie-d|😭|cried', 't-r-ie-d', 'f-l-ie-s|🪰|flies', 'd-r-ie-d'],
  ue: ['b-l-ue|🔵|blue', 'c-l-ue|🔍|clue', 'g-l-ue', 't-r-ue', 'c-ue', 'd-ue', 'r-e-s-c-ue', 'v-a-l-ue', 'ar-g-ue', 's-t-a-t-ue|🗽|statue', 'i-ss-ue'],
  'u-yoo': ['u-n-i-t@u-yoo', 'm-u-s-i-c@u-yoo|🎵|music', 'm-e-n-u@u-yoo|📋|menu', 't-u-l-i-p@u-yoo|🌷|tulip', 's-u-p-er@u-yoo', 'p-u-p-i-l@u-yoo', 'h-u-m-a-n@u-yoo', 'u-n-i-f-or-m@u-yoo', 's-t-u-d-e-n-t@u-yoo'],
  'o-oa': ['o-l-d@o-oa', 'c-o-l-d@o-oa|🥶|cold', 'g-o-l-d@o-oa|🥇|gold', 'h-o-l-d@o-oa', 't-o-l-d@o-oa', 'b-o-th@o-oa', 'm-o-s-t@o-oa', 'p-o-s-t@o-oa|📮|post', 'h-e-ll-o@o-oa|👋|hello', 'o-p-e-n@o-oa', 'r-o-b-o-t@o-oa|🤖|robot'],
  'i-igh': ['f-i-n-d@i-igh', 'k-i-n-d@i-igh', 'm-i-n-d@i-igh', 'w-i-l-d@i-igh', 'ch-i-l-d@i-igh|🧒|child', 'm-i-l-d@i-igh', 'b-l-i-n-d@i-igh', 't-i-g-er@i-igh|🐯|tiger', 's-p-i-d-er@i-igh', 'b-e-h-i-n-d@i-igh'],
  'a-ai': ['a-c-or-n@a-ai|🌰|acorn', 'p-a-p-er@a-ai|📄|paper', 'l-a-t-er@a-ai', 'l-a-b-e-l@a-ai|🏷️|label', 'b-a-k-er@a-ai'],
  'e-ee': ['e-v-e-n@e-ee', 's-e-c-r-e-t@e-ee', 'f-e-v-er@e-ee|🌡️|fever', 'm-e-t-er@e-ee', 'z-e-r-o@e-ee+o-oa|0️⃣|zero', 'z-e-b-r-a@e-ee|🦓|zebra', 'h-e-r-o@e-ee+o-oa|🦸|hero'],
  'split-a': ['c-a_e-k|🎂|cake', 'm-a_e-k', 't-a_e-k', 'n-a_e-m', 'g-a_e-m|🎮|game', 'c-a_e-m', 'g-a_e-t', 'l-a_e-t', 's-a_e-f', 's-a_e-m', 't-a_e-p', 'c-a_e-v', 'w-a_e-v', 'l-a_e-k', 'b-a_e-k', 'sh-a_e-k', 's-n-a_e-k', 'p-l-a_e-t|🍽️|plate', 'g-r-a_e-p|🍇|grape', 'w-a_e-k', 's-k-a_e-t', 'c-a_e-k-s|🎂|cakes', 't-a_e-k-s'],
  'split-i': ['b-i_e-k|🚲|bike', 'f-i_e-v|5️⃣|five', 't-i_e-m', 'n-i_e-n|9️⃣|nine', 'l-i_e-n', 's-m-i_e-l', 's-l-i_e-d', 'r-i_e-d', 'h-i_e-d', 's-i_e-d', 'k-i_e-t|🪁|kite', 'm-i_e-n', 'f-i_e-n', 'p-i_e-p', 'w-i_e-p', 'd-i_e-v', 'd-r-i_e-v', 'sh-i_e-n', 'b-i_e-t', 'k-i_e-t-s|🪁|kites', 'b-i_e-k-s|🚲|bikes'],
  'split-o': ['h-o_e-m|🏠|home', 'b-o_e-n|🦴|bone', 'n-o_e-s|👃|nose', 'r-o_e-p', 'h-o_e-l', 's-t-o_e-n', 'j-o_e-k', 'n-o_e-t', 'h-o_e-p', 'r-o_e-s|🌹|rose', 'p-o_e-k', 'w-o_e-k', 'th-o_e-s@th-voiced', 'c-o_e-d', 'c-o_e-n|🍦|cone', 'g-l-o_e-b|🌍|globe', 's-m-o_e-k', 's-p-o_e-k', 'b-o_e-n-s|🦴|bones'],
  'split-u': ['c-u_e-b', 'c-u_e-t', 't-u_e-n', 'r-u_e-l', 't-u_e-b|🧪|tube', 'f-l-u_e-t', 'r-u_e-d', 'u_e-s', 'f-u_e-s', 'd-u_e-n', 'p-l-u_e-m', 'c-u_e-b-s', 't-u_e-n-s'],
  'split-e': ['th-e_e-s@th-voiced', 'th-e_e-m', 'e_e-v', 'e-x-t-r-e_e-m', 'c-o-m-p-l-e_e-t', 'd-e-l-e_e-t'],
  ew: ['n-ew', 'f-ew', 'd-ew', 'ch-ew', 'b-l-ew', 'f-l-ew', 'g-r-ew', 'd-r-ew', 'th-r-ew', 'c-r-ew', 's-t-ew', 'n-ew-s', 'j-ew-e-l|💎|jewel'],
  'ie-ee': ['f-ie-l-d@ie-ee', 'ch-ie-f@ie-ee', 'sh-ie-l-d@ie-ee|🛡️|shield', 'b-r-ie-f@ie-ee', 'r-e-l-ie-f@ie-ee', 'b-e-l-ie-f@ie-ee', 'b-e-l-ie-v-e@ie-ee'],
  aw: ['s-aw', 'p-aw|🐾|paw', 'j-aw', 'r-aw', 'c-l-aw', 'd-r-aw', 's-t-r-aw|🥤|straw', 'y-aw-n|🥱|yawn', 'l-aw-n', 'c-r-aw-l', 'd-aw-n', 'h-aw-k|🦅|hawk', 'l-aw', 'sh-aw-l'],
  wh: ['wh-i-p', 'wh-i-s-k', 'wh-i_e-t@wh', 'wh-ee-l|🛞|wheel', 'wh-a_e-l|🐋|whale', 'wh-i_e-l', 'wh-i-ch', 'wh-ea-t|🌾|wheat', 'wh-i-s-p-er', 'wh-i-m', 'wh-i-ff'],
  oe: ['t-oe', 'd-oe|🦌|doe', 'f-oe', 'h-oe', 'g-oe-s', 't-i-p-t-oe', 'w-oe'],
  'ou-oa': ['sh-ou-l-d-er@ou-oa', 'b-ou-l-d-er@ou-oa|🪨|boulder', 'm-ou-l-d@ou-oa', 's-ou-l@ou-oa', 'm-ou-l-t@ou-oa'],
  ph: ['ph-o_e-n|📱|phone', 'ph-o-t-o@o-oa|📷|photo', 'd-o-l-ph-i-n|🐬|dolphin', 'e-l-e-ph-a-n-t|🐘|elephant', 'a-l-ph-a-b-e-t|🔤|alphabet', 'g-r-a-ph', 'ph-o-n-i-c-s', 'n-e-ph-ew'],
  au: ['h-au-l', 'l-au-n-ch|🚀|launch', 'f-au-l-t', 'v-au-l-t', 'c-au-s-e', 'p-au-s-e', 'a-s-t-r-o-n-au-t|🧑‍🚀|astronaut', 'd-i-n-o-s-au-r@i-igh|🦖|dinosaur', 'a-p-p-l-au-d|👏|applaud', 'au-th-or', 'b-e-c-au-s-e'],
  ey: ['k-ey|🔑|key', 't-ur-k-ey|🦃|turkey', 'v-a-ll-ey', 't-r-o-ll-ey|🛒|trolley', 'h-o-ck-ey|🏑|hockey', 'j-o-ck-ey', 'ch-i-m-n-ey', 'a-ll-ey', 'b-ar-l-ey', 'p-ar-s-l-ey', 'k-i-d-n-ey'],
  'ow-oa': ['s-n-ow@ow-oa|❄️|snow', 'sh-ow@ow-oa', 'g-r-ow@ow-oa', 'b-l-ow@ow-oa', 's-l-ow@ow-oa', 'l-ow@ow-oa', 'b-ow-l@ow-oa|🥣|bowl', 'ow-n@ow-oa', 'c-r-ow@ow-oa|🐦‍⬛|crow', 'th-r-ow@ow-oa', 'w-i-n-d-ow@ow-oa|🪟|window', 'y-e-ll-ow@ow-oa|🟡|yellow', 'p-i-ll-ow@ow-oa', 'r-ai-n-b-ow@ow-oa|🌈|rainbow', 'e-l-b-ow@ow-oa'],
  'ea-e': ['h-ea-d@ea-e', 'b-r-ea-d@ea-e|🍞|bread', 'b-r-ea-k-f-a-s-t@ea-e', 'f-ea-th-er@ea-e+th-voiced|🪶|feather', 'w-ea-th-er@ea-e+th-voiced', 'h-ea-l-th@ea-e', 's-w-ea-t@ea-e', 'th-r-ea-d@ea-e|🧵|thread', 's-p-r-ea-d@ea-e', 'i-n-s-t-ea-d@ea-e'],
  'y-igh': ['f-l-y@y-igh|🪰|fly', 'c-r-y@y-igh|😭|cry', 't-r-y@y-igh', 's-k-y@y-igh', 'd-r-y@y-igh', 'wh-y@y-igh', 'f-r-y@y-igh', 'sh-y@y-igh', 's-p-y@y-igh', 'r-e-p-l-y@y-igh'],
  'y-ee': ['h-a-p-p-y@y-ee|😊|happy', 'f-u-n-n-y@y-ee', 's-u-n-n-y@y-ee', 'b-a-b-y@a-ai+y-ee|👶|baby', 'p-u-p-p-y@y-ee|🐶|puppy', 'b-u-n-n-y@y-ee|🐰|bunny', 'p-e-n-n-y@y-ee', 'j-e-ll-y@y-ee', 'l-u-ck-y@y-ee|🍀|lucky', 'm-u-d-d-y@y-ee', 's-i-ll-y@y-ee|🤪|silly', 'm-e-ss-y@y-ee', 'w-i-n-d-y@y-ee|🌬️|windy', 'p-o-n-y@o-oa+y-ee|🐴|pony', 'l-a-d-y@a-ai+y-ee', 'h-ea-v-y@ea-e+y-ee', 'r-ea-d-y@ea-e+y-ee', 't-r-o-ph-y@o-oa+y-ee+ph|🏆|trophy'],
  'c-s': ['c-i-t-y@c-s+y-ee|🏙️|city', 'c-e-n-t@c-s', 'f-a_e-c@c-s|🙂|face', 'r-a_e-c@c-s|🏁|race', 'i_e-c@c-s|🧊|ice', 'r-i_e-c@c-s|🍚|rice', 'm-i_e-c@c-s|🐭|mice', 'n-i_e-c@c-s', 's-p-a_e-c@c-s', 'p-e-n-c-i-l@c-s|✏️|pencil', 'd-a-n-c-e@c-s|💃|dance', 'c-i-r-c-u-s@c-s|🎪|circus', 'f-a-n-c-y@c-s+y-ee', 'v-oi-c-e@c-s', 'p-l-a_e-c@c-s'],
  'g-j': ['g-e-m@g-j|💎|gem', 'g-e-n-t-l-e@g-j', 'g-i-r-a-ff-e@g-j|🦒|giraffe', 'm-a-g-i-c@g-j|✨|magic', 'p-a_e-g@g-j', 'c-a_e-g@g-j', 's-t-a_e-g@g-j', 'a_e-g@g-j', 'ch-a-n-g-e@g-j+a-ai', 'o-r-a-n-g-e@g-j|🍊|orange', 'g-i-a-n-t@g-j+i-igh', 'h-u_e-g@g-j', 'g-i-n-g-er@g-j', 'g-e_e-n@g-j', 'd-a-n-g-er@g-j+a-ai'],
  dge: ['e-dge', 'b-a-dge|🏅|badge', 'f-u-dge', 'l-o-dge', 'h-e-dge', 'r-i-dge', 'b-r-i-dge|🌉|bridge', 'j-u-dge|⚖️|judge', 'd-o-dge', 'w-e-dge', 's-m-u-dge', 'p-l-e-dge'],
  tch: ['c-a-tch', 'm-a-tch', 'p-a-tch', 'h-a-tch', 'f-e-tch', 'w-i-tch|🧙|witch', 'k-i-tch-e-n', 'p-i-tch', 'd-i-tch', 'h-u-tch', 'n-o-tch', 'i-tch', 's-t-i-tch', 's-k-e-tch', 's-t-r-e-tch'],
  kn: ['kn-ee', 'kn-i-t', 'kn-o-t', 'kn-o-ck|🚪|knock', 'kn-ew', 'kn-ow@ow-oa', 'kn-igh-t', 'kn-ee-l', 'kn-o-b|🔘|knob', 'kn-a-ck', 'kn-ow-n@ow-oa'],
  wr: ['wr-a-p', 'wr-e-n', 'wr-i-s-t', 'wr-o-ng', 'wr-i_e-t|✍️|write', 'wr-o_e-t', 'wr-e-ck', 'wr-ea-th', 'wr-e-n-ch', 'wr-i-nk-l-e', 'wr-i-g-g-l-e'],
  mb: ['l-a-mb', 'th-u-mb|👍|thumb', 'c-o-mb@o-oa', 'c-l-i-mb@i-igh|🧗|climb', 'c-r-u-mb', 'l-i-mb', 'n-u-mb', 'p-l-u-mb-er'],
  gn: ['gn-a-t|🦟|gnat', 'gn-aw', 'gn-o_e-m', 's-i-gn@i-igh|🪧|sign', 'd-e-s-i-gn@i-igh', 'a-l-i-gn@i-igh', 'gn-a-sh', 'r-e-s-i-gn@i-igh'],
  'ch-k': ['s-ch-oo-l@ch-k|🏫|school', 'e-ch-o@ch-k+o-oa', 'a-ch-e@ch-k+a-ai', 'a-n-ch-or@ch-k|⚓|anchor', 's-t-o-m-a-ch@ch-k', 'ch-or-u-s@ch-k', 'ch-e-m-i-s-t@ch-k', 'ch-a-o-s@ch-k+a-ai', 'ch-or-d@ch-k|🎼|chord', 'ch-a-r-a-c-t-er@ch-k'],
  'ch-sh': ['ch-e-f@ch-sh', 'p-a-r-a-ch-u_e-t@ch-sh|🪂|parachute', 'ch-u_e-t@ch-sh'],
  'a-o': ['w-a-sh@a-o', 's-w-a-n@a-o|🦢|swan', 'w-a-s-p@a-o', 's-w-a-p@a-o|🔄|swap', 'w-a-ll-e-t@a-o|👛|wallet', 'w-a-n-d@a-o|🪄|wand', 'w-a-tch@a-o|⌚|watch', 's-w-a-m-p@a-o', 's-qu-a-sh@a-o', 's-qu-a-d@a-o'],
  'or-ur': ['w-or-d@or-ur', 'w-or-k@or-ur', 'w-or-l-d@or-ur|🌍|world', 'w-or-m@or-ur', 'w-or-s-e@or-ur', 'w-or-th@or-ur', 'w-or-s-t@or-ur'],
  ture: ['p-i-c-ture|🖼️|picture', 'n-a-ture@a-ai|🌿|nature', 'a-d-v-e-n-ture', 'f-u-ture@u-yoo', 'c-a-p-ture', 'c-r-ea-ture', 'f-ur-n-i-ture', 'm-i-x-ture', 'm-oi-s-ture', 'c-u-l-ture', 't-e-x-ture', 'f-ea-ture'],
  'tion-sion': ['s-t-a-tion@a-ai|🚉|station', 'a-c-tion', 'n-a-tion@a-ai', 'm-o-tion@o-oa', 'l-o-tion@o-oa|🧴|lotion', 'p-o-tion@o-oa', 'f-i-c-tion', 'm-e-n-tion', 'v-i-sion', 't-e-l-e-v-i-sion|📺|television', 'd-e-c-i-sion@c-s', 'i-n-v-e-n-tion', 'd-i-r-e-c-tion'],
};
